version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lamp
      MYSQL_USER: lamp_docker
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
  app-8.2:
    image: php:8.2.0RC5-apache-buster
    volumes:
      - "./app:/var/www/html"
    ports:
      - 82:80
  app-8.1:
    image: php:8.1.12-apache-buster
    volumes:
      - "./app:/var/www/html"
    ports:
      - 81:80      
  app-8.0:
    image: php:8.0-apache-buster
    volumes:
      - "./app:/var/www/html"
    ports:
      - 80:80     
  app-7.4:
    image: php:7.4-apache-buster
    volumes:
      - "./app:/var/www/html"
    ports:
      - 74:80
  app-7.3:
    image: php:7.3-apache-buster
    volumes:
      - "./app:/var/www/html"
    ports:
      - 73:80
  app-7.2:
    image: php:7.2-apache-buster
    volumes:
      - "./app:/var/www/html"
    ports:
      - 72:80
  app-7.1:
    image: php:7.1-apache-buster
    volumes:
      - "./app:/var/www/html"
    ports:
      - 71:80
  app-7.0:
    image: php:7.0-apache-jessie
    volumes:
      - "./app:/var/www/html"
    ports:
      - 70:80
  app-5.6:
    image: php:5.6-apache-jessie
    volumes:
      - "./app:/var/www/html"
    ports:
      - 56:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306